package com.unishare.api.modules.service.exception;

import com.unishare.api.common.dto.ExceptionCode;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ServiceErrorCode implements ExceptionCode {
    SERVICE_VERSION_NOT_FOUND(404, "SERVICE_VERSION_NOT_FOUND"),
    PACKAGE_INACTIVE(400, "PACKAGE_INACTIVE"),
    PACKAGE_NOT_FOUND(404, "PACKAGE_NOT_FOUND"),
    PACKAGE_ALREADY_ARCHIVED(409, "PACKAGE_ALREADY_ARCHIVED"),
    CURRICULUM_NOT_FOUND(404, "CURRICULUM_NOT_FOUND"),
    PACKAGE_CURRICULUM_REQUIRED(400, "PACKAGE_CURRICULUM_REQUIRED"),
    DUPLICATE_CURRICULUM_ORDER_INDEX(400, "DUPLICATE_CURRICULUM_ORDER_INDEX"),
    VERSION_HAS_ACTIVE_ORDERS(409, "VERSION_HAS_ACTIVE_ORDERS"),
    CANNOT_DELETE_DEFAULT_VERSION(409, "CANNOT_DELETE_DEFAULT_VERSION"),
    PACKAGE_MUST_HAVE_VERSION(400, "PACKAGE_MUST_HAVE_VERSION");

    private final Integer code;
    private final String type;
}
